import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
const cors = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type', 'Content-Type': 'application/json' }
const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: cors })
function decimalToRaw(value: string | number, decimals: number): bigint { const normalized = String(value).trim(); if (!/^\d+(\.\d+)?$/.test(normalized)) throw new Error('Invalid payment amount.'); const [whole, fraction = ''] = normalized.split('.'); if (fraction.length > decimals && /[^0]/.test(fraction.slice(decimals))) throw new Error('Payment amount has more precision than the token supports.'); return BigInt(whole) * (10n ** BigInt(decimals)) + BigInt(fraction.slice(0, decimals).padEnd(decimals, '0') || '0') }
async function sha256Hex(value: string) { const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return Array.from(new Uint8Array(digest)).map(b => b.toString(16).padStart(2, '0')).join('') }
Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors })
  try {
    const { order_id, registration_token, tx_hash } = await req.json(); const orderId = String(order_id ?? '').trim(); const token = String(registration_token ?? '').trim(); const txHash = String(tx_hash ?? '').trim()
    if (!orderId || !token || !txHash) throw new Error('Registration order, token and transaction hash are required.')
    if (!/^[0-9a-f]{64}$/i.test(txHash)) throw new Error('Enter a valid 64-character TRON transaction hash.')
    const db = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!); const tokenHash = await sha256Hex(token)
    const { data: order, error: orderError } = await db.from('registration_orders').select('*').eq('id', orderId).eq('registration_token_hash', tokenHash).single(); if (orderError || !order) throw new Error('Registration order not found.')
    if (new Date(order.expires_at).getTime() <= Date.now()) { await db.from('registration_orders').update({ status: 'expired' }).eq('id', order.id); throw new Error('This registration payment session has expired. Please start again.') }
    if (order.status === 'payment_verified') return response({ verified: true, message: 'Payment already verified.' }); if (order.status !== 'pending_payment') throw new Error('This registration order is no longer payable.'); if (Number(order.verification_attempts) >= 10) throw new Error('Too many verification attempts. Please start a new registration order.')
    const { data: duplicate } = await db.from('registration_orders').select('id').eq('tx_hash', txHash).neq('id', order.id).maybeSingle(); if (duplicate) throw new Error('This transaction hash has already been submitted.')
    const { data: usedPayment } = await db.from('registration_payments').select('id').eq('tx_hash', txHash).maybeSingle(); if (usedPayment) throw new Error('This transaction hash has already been used.')
    await db.from('registration_orders').update({ tx_hash: txHash, verification_attempts: Number(order.verification_attempts) + 1 }).eq('id', order.id)
    const { data: config } = await db.from('payment_config').select('*').eq('active', true).limit(1).single(); if (!config || String(config.wallet_address).startsWith('CONFIGURE_')) throw new Error('Payment wallet is not configured by the administrator.'); const contract = String(config.usdt_contract ?? Deno.env.get('TRON_USDT_CONTRACT') ?? '').trim(); if (!contract) throw new Error('TRON USDT contract is not configured.')
    let tx: any = null; let fingerprint: string | undefined; const apiKey = Deno.env.get('TRONGRID_API_KEY') ?? ''
    for (let page = 0; page < 5 && !tx; page++) { const url = new URL(`https://api.trongrid.io/v1/accounts/${config.wallet_address}/transactions/trc20`); url.searchParams.set('only_confirmed','true'); url.searchParams.set('limit','200'); url.searchParams.set('contract_address',contract); if (fingerprint) url.searchParams.set('fingerprint',fingerprint); const r = await fetch(url,{headers:apiKey?{'TRON-PRO-API-KEY':apiKey}:{}}); if(!r.ok) throw new Error(`TRON verification service returned ${r.status}.`); const payload=await r.json(); tx=(payload.data??[]).find((item:any)=>String(item.transaction_id).toLowerCase()===txHash.toLowerCase()); fingerprint=payload.meta?.fingerprint; if(!fingerprint) break }
    if (!tx) { await db.from('registration_orders').update({ verification_error: 'Transaction not found or not confirmed on TRON.' }).eq('id', order.id); return response({ verified:false, message:'Transaction not found or not yet confirmed on TRON.' }) }
    const decimals=Number(tx.token_info?.decimals??6); const amountMatches=BigInt(String(tx.value))===decimalToRaw(order.amount,decimals); const toMatches=String(tx.to??'').toLowerCase()===String(config.wallet_address).toLowerCase(); const tokenMatches=String(tx.token_info?.address??'').toLowerCase()===contract.toLowerCase()
    if(!toMatches||!tokenMatches||!amountMatches){const reason=!toMatches?'Recipient wallet does not match.':!tokenMatches?'Token contract does not match USDT on TRON.':'Payment amount does not exactly match the required registration fee.'; await db.from('registration_orders').update({verification_error:reason}).eq('id',order.id); return response({verified:false,message:reason})}
    const { error: paymentError } = await db.from('registration_payments').insert({ registration_order_id:order.id, amount:order.amount, currency:order.currency, asset:'USDT', network:'TRON', wallet_address:config.wallet_address, tx_hash:txHash, status:'verified' }); if(paymentError) throw new Error(paymentError.message)
    const { error: updateError } = await db.from('registration_orders').update({status:'payment_verified',verification_error:null,verified_at:new Date().toISOString()}).eq('id',order.id).eq('status','pending_payment'); if(updateError) throw updateError
    return response({verified:true,message:'Payment verified. You can now create your GILSE account.'})
  } catch(error){ return response({verified:false,message:error instanceof Error?error.message:'Verification failed.'},400) }
})
