create schema if not exists maher_ai;

create table if not exists maher_ai.profiles(user_id uuid primary key references auth.users(id) on delete cascade,full_name text,headline text,location text,summary text,preferences jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists maher_ai.skills(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,name text not null,level text,evidence text,created_at timestamptz not null default now());
create table if not exists maher_ai.experiences(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,employer text,role text not null,location text,start_date date,end_date date,description text,achievements jsonb not null default '[]'::jsonb,created_at timestamptz not null default now());
create table if not exists maher_ai.documents(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,document_type text not null,title text,storage_path text,extracted_text text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists maher_ai.jobs(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,title text not null,organization text,location text,country text,source_url text,description text,requirements jsonb not null default '[]'::jsonb,match_score numeric(5,2),match_evidence jsonb not null default '[]'::jsonb,status text not null default 'saved',created_at timestamptz not null default now());
create table if not exists maher_ai.applications(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,job_id bigint references maher_ai.jobs(id) on delete set null,status text not null default 'draft',cv_version text,cover_letter text,notes text,submitted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists maher_ai.knowledge_sources(id bigint generated always as identity primary key,user_id uuid references auth.users(id) on delete cascade,title text not null,url text,source_type text,publisher text,published_at timestamptz,trust_level text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists maher_ai.knowledge_chunks(id bigint generated always as identity primary key,source_id bigint references maher_ai.knowledge_sources(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,content text not null,embedding extensions.vector(384),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists maher_ai.research_tasks(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,question text not null,verification_targets jsonb not null default '[]'::jsonb,status text not null default 'queued',findings text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists maher_ai.research_sources(id bigint generated always as identity primary key,task_id bigint references maher_ai.research_tasks(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,url text not null,title text,source_type text,accessed_at timestamptz not null default now(),excerpt text,claims jsonb not null default '[]'::jsonb);
create table if not exists maher_ai.business_ideas(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,name text not null,hypothesis text,target_customer text,value_proposition text,estimated_cost text,evidence jsonb not null default '[]'::jsonb,status text not null default 'idea',created_at timestamptz not null default now());
create table if not exists maher_ai.experiments(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,idea_id bigint references maher_ai.business_ideas(id) on delete cascade,hypothesis text,test_plan text,success_metric text,budget_limit numeric,status text not null default 'planned',created_at timestamptz not null default now());
create table if not exists maher_ai.experiment_results(id bigint generated always as identity primary key,experiment_id bigint references maher_ai.experiments(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,result text,metrics jsonb not null default '{}'::jsonb,lessons text,created_at timestamptz not null default now());
create table if not exists maher_ai.agent_tasks(id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,task_type text not null,input jsonb not null default '{}'::jsonb,status text not null default 'queued',priority integer not null default 50,requires_approval boolean not null default false,created_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists maher_ai.agent_runs(id bigint generated always as identity primary key,task_id bigint references maher_ai.agent_tasks(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,provider text,model text,input_tokens integer,output_tokens integer,status text not null default 'started',trace jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

create index if not exists knowledge_chunks_source_idx on maher_ai.knowledge_chunks(source_id);
create index if not exists jobs_user_status_idx on maher_ai.jobs(user_id,status);
create index if not exists applications_user_status_idx on maher_ai.applications(user_id,status);
create index if not exists research_tasks_user_status_idx on maher_ai.research_tasks(user_id,status);
create index if not exists agent_tasks_user_status_idx on maher_ai.agent_tasks(user_id,status);

do $$ declare t text; begin
foreach t in array array['profiles','skills','experiences','documents','jobs','applications','knowledge_sources','knowledge_chunks','research_tasks','research_sources','business_ideas','experiments','experiment_results','agent_tasks','agent_runs'] loop
execute format('alter table maher_ai.%I enable row level security',t);
execute format('drop policy if exists owner_select on maher_ai.%I',t);
execute format('drop policy if exists owner_insert on maher_ai.%I',t);
execute format('drop policy if exists owner_update on maher_ai.%I',t);
execute format('drop policy if exists owner_delete on maher_ai.%I',t);
execute format('create policy owner_select on maher_ai.%I for select to authenticated using (user_id=(select auth.uid()))',t);
execute format('create policy owner_insert on maher_ai.%I for insert to authenticated with check (user_id=(select auth.uid()))',t);
execute format('create policy owner_update on maher_ai.%I for update to authenticated using (user_id=(select auth.uid())) with check (user_id=(select auth.uid()))',t);
execute format('create policy owner_delete on maher_ai.%I for delete to authenticated using (user_id=(select auth.uid()))',t);
end loop; end $$;